/*
 * MicrosimView.java
 */

package microsim;

import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 * The application's main frame.
 */
public class MicrosimView extends FrameView {

    public MicrosimView(SingleFrameApplication app) {
        super(app);

        initComponents();

        // status bar initialization - message timeout, idle icon and busy animation, etc
        ResourceMap resourceMap = getResourceMap();
        int messageTimeout = resourceMap.getInteger("StatusBar.messageTimeout");
        messageTimer = new Timer(messageTimeout, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                statusMessageLabel.setText("");
            }
        });
        messageTimer.setRepeats(false);
        int busyAnimationRate = resourceMap.getInteger("StatusBar.busyAnimationRate");
        for (int i = 0; i < busyIcons.length; i++) {
            busyIcons[i] = resourceMap.getIcon("StatusBar.busyIcons[" + i + "]");
        }
        busyIconTimer = new Timer(busyAnimationRate, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                busyIconIndex = (busyIconIndex + 1) % busyIcons.length;
                statusAnimationLabel.setIcon(busyIcons[busyIconIndex]);
            }
        });
        idleIcon = resourceMap.getIcon("StatusBar.idleIcon");
        statusAnimationLabel.setIcon(idleIcon);
        progressBar.setVisible(false);

        // connecting action tasks to status bar via TaskMonitor
        TaskMonitor taskMonitor = new TaskMonitor(getApplication().getContext());
        taskMonitor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                String propertyName = evt.getPropertyName();
                if ("started".equals(propertyName)) {
                    if (!busyIconTimer.isRunning()) {
                        statusAnimationLabel.setIcon(busyIcons[0]);
                        busyIconIndex = 0;
                        busyIconTimer.start();
                    }
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(true);
                } else if ("done".equals(propertyName)) {
                    busyIconTimer.stop();
                    statusAnimationLabel.setIcon(idleIcon);
                    progressBar.setVisible(false);
                    progressBar.setValue(0);
                } else if ("message".equals(propertyName)) {
                    String text = (String)(evt.getNewValue());
                    statusMessageLabel.setText((text == null) ? "" : text);
                    messageTimer.restart();
                } else if ("progress".equals(propertyName)) {
                    int value = (Integer)(evt.getNewValue());
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(false);
                    progressBar.setValue(value);
                }
            }
        });
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = MicrosimApp.getApplication().getMainFrame();
            aboutBox = new MicrosimAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        MicrosimApp.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        IRLabel = new javax.swing.JLabel();
        PCLabel = new javax.swing.JLabel();
        ALabel = new javax.swing.JLabel();
        R0Label = new javax.swing.JLabel();
        R1Label = new javax.swing.JLabel();
        R2Label = new javax.swing.JLabel();
        R3Label = new javax.swing.JLabel();
        R4Label = new javax.swing.JLabel();
        R5Label = new javax.swing.JLabel();
        R6Label = new javax.swing.JLabel();
        R7Label = new javax.swing.JLabel();
        IRField = new javax.swing.JTextField();
        PCField = new javax.swing.JTextField();
        AField = new javax.swing.JTextField();
        R0Field = new javax.swing.JTextField();
        R0Field1 = new javax.swing.JTextField();
        R2Field = new javax.swing.JTextField();
        R3Field = new javax.swing.JTextField();
        R4Field = new javax.swing.JTextField();
        R5Field = new javax.swing.JTextField();
        R6Field = new javax.swing.JTextField();
        R7Field = new javax.swing.JTextField();
        SRLabel = new javax.swing.JLabel();
        SRField = new javax.swing.JTextField();
        KeyboardLabel = new javax.swing.JLabel();
        DisplayLabel = new javax.swing.JLabel();
        MemoryLabel = new javax.swing.JLabel();
        KeyboardField = new javax.swing.JTextField();
        DisplayField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        MemoryList = new javax.swing.JList();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
        statusPanel = new javax.swing.JPanel();
        javax.swing.JSeparator statusPanelSeparator = new javax.swing.JSeparator();
        statusMessageLabel = new javax.swing.JLabel();
        statusAnimationLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        PCField1 = new javax.swing.JTextField();

        mainPanel.setName("mainPanel"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(microsim.MicrosimApp.class).getContext().getResourceMap(MicrosimView.class);
        IRLabel.setText(resourceMap.getString("IRLabel.text")); // NOI18N
        IRLabel.setName("IRLabel"); // NOI18N

        PCLabel.setText(resourceMap.getString("PCLabel.text")); // NOI18N
        PCLabel.setName("PCLabel"); // NOI18N

        ALabel.setText(resourceMap.getString("ALabel.text")); // NOI18N
        ALabel.setName("ALabel"); // NOI18N

        R0Label.setText(resourceMap.getString("R0Label.text")); // NOI18N
        R0Label.setName("R0Label"); // NOI18N

        R1Label.setText(resourceMap.getString("R1Label.text")); // NOI18N
        R1Label.setName("R1Label"); // NOI18N

        R2Label.setText(resourceMap.getString("R2Label.text")); // NOI18N
        R2Label.setName("R2Label"); // NOI18N

        R3Label.setText(resourceMap.getString("R3Label.text")); // NOI18N
        R3Label.setName("R3Label"); // NOI18N

        R4Label.setText(resourceMap.getString("R4Label.text")); // NOI18N
        R4Label.setName("R4Label"); // NOI18N

        R5Label.setText(resourceMap.getString("R5Label.text")); // NOI18N
        R5Label.setName("R5Label"); // NOI18N

        R6Label.setText(resourceMap.getString("R6Label.text")); // NOI18N
        R6Label.setName("R6Label"); // NOI18N

        R7Label.setText(resourceMap.getString("R7Label.text")); // NOI18N
        R7Label.setName("R7Label"); // NOI18N

        IRField.setEditable(false);
        IRField.setText(resourceMap.getString("IRField.text")); // NOI18N
        IRField.setMaximumSize(new java.awt.Dimension(16, 1));
        IRField.setMinimumSize(new java.awt.Dimension(16, 1));
        IRField.setName("IRField"); // NOI18N
        IRField.setPreferredSize(new java.awt.Dimension(16, 1));

        PCField.setEditable(false);
        PCField.setMaximumSize(new java.awt.Dimension(8, 1));
        PCField.setMinimumSize(new java.awt.Dimension(8, 1));
        PCField.setName("PCField"); // NOI18N
        PCField.setPreferredSize(new java.awt.Dimension(8, 1));

        AField.setEditable(false);
        AField.setMaximumSize(new java.awt.Dimension(8, 1));
        AField.setMinimumSize(new java.awt.Dimension(8, 1));
        AField.setName("AField"); // NOI18N
        AField.setPreferredSize(new java.awt.Dimension(8, 1));

        R0Field.setEditable(false);
        R0Field.setMaximumSize(new java.awt.Dimension(8, 1));
        R0Field.setMinimumSize(new java.awt.Dimension(8, 1));
        R0Field.setName("R0Field"); // NOI18N
        R0Field.setPreferredSize(new java.awt.Dimension(8, 1));

        R0Field1.setEditable(false);
        R0Field1.setMaximumSize(new java.awt.Dimension(8, 1));
        R0Field1.setMinimumSize(new java.awt.Dimension(8, 1));
        R0Field1.setName("R0Field1"); // NOI18N
        R0Field1.setPreferredSize(new java.awt.Dimension(8, 1));

        R2Field.setEditable(false);
        R2Field.setMaximumSize(new java.awt.Dimension(8, 1));
        R2Field.setMinimumSize(new java.awt.Dimension(8, 1));
        R2Field.setName("R2Field"); // NOI18N
        R2Field.setPreferredSize(new java.awt.Dimension(8, 1));

        R3Field.setEditable(false);
        R3Field.setMaximumSize(new java.awt.Dimension(8, 1));
        R3Field.setMinimumSize(new java.awt.Dimension(8, 1));
        R3Field.setName("R3Field"); // NOI18N
        R3Field.setPreferredSize(new java.awt.Dimension(8, 1));

        R4Field.setEditable(false);
        R4Field.setMaximumSize(new java.awt.Dimension(8, 1));
        R4Field.setMinimumSize(new java.awt.Dimension(8, 1));
        R4Field.setName("R4Field"); // NOI18N
        R4Field.setPreferredSize(new java.awt.Dimension(8, 1));

        R5Field.setEditable(false);
        R5Field.setMaximumSize(new java.awt.Dimension(8, 1));
        R5Field.setMinimumSize(new java.awt.Dimension(8, 1));
        R5Field.setName("R5Field"); // NOI18N
        R5Field.setPreferredSize(new java.awt.Dimension(8, 1));

        R6Field.setEditable(false);
        R6Field.setMaximumSize(new java.awt.Dimension(8, 1));
        R6Field.setMinimumSize(new java.awt.Dimension(8, 1));
        R6Field.setName("R6Field"); // NOI18N
        R6Field.setPreferredSize(new java.awt.Dimension(8, 1));

        R7Field.setEditable(false);
        R7Field.setMaximumSize(new java.awt.Dimension(8, 1));
        R7Field.setMinimumSize(new java.awt.Dimension(8, 1));
        R7Field.setName("R7Field"); // NOI18N
        R7Field.setPreferredSize(new java.awt.Dimension(8, 1));

        SRLabel.setText(resourceMap.getString("SRLabel.text")); // NOI18N
        SRLabel.setName("SRLabel"); // NOI18N

        SRField.setEditable(false);
        SRField.setMaximumSize(new java.awt.Dimension(4, 1));
        SRField.setMinimumSize(new java.awt.Dimension(4, 1));
        SRField.setName("SRField"); // NOI18N
        SRField.setPreferredSize(new java.awt.Dimension(4, 1));

        KeyboardLabel.setText(resourceMap.getString("KeyboardLabel.text")); // NOI18N
        KeyboardLabel.setName("KeyboardLabel"); // NOI18N

        DisplayLabel.setText(resourceMap.getString("DisplayLabel.text")); // NOI18N
        DisplayLabel.setName("DisplayLabel"); // NOI18N

        MemoryLabel.setText(resourceMap.getString("MemoryLabel.text")); // NOI18N
        MemoryLabel.setName("MemoryLabel"); // NOI18N

        KeyboardField.setEditable(false);
        KeyboardField.setMaximumSize(new java.awt.Dimension(1, 1));
        KeyboardField.setMinimumSize(new java.awt.Dimension(1, 1));
        KeyboardField.setName("KeyboardField"); // NOI18N
        KeyboardField.setPreferredSize(new java.awt.Dimension(1, 1));

        DisplayField.setEditable(false);
        DisplayField.setMaximumSize(new java.awt.Dimension(4, 1));
        DisplayField.setMinimumSize(new java.awt.Dimension(4, 1));
        DisplayField.setName("DisplayField"); // NOI18N
        DisplayField.setPreferredSize(new java.awt.Dimension(4, 1));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        MemoryList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        MemoryList.setName("MemoryList"); // NOI18N
        jScrollPane1.setViewportView(MemoryList);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(R7Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(R7Field, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
                                    .addComponent(R0Label)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(R0Field, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(MemoryLabel))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
                                    .addComponent(ALabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(AField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DisplayLabel))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
                                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(IRLabel)
                                        .addComponent(PCLabel))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                            .addComponent(PCField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(KeyboardLabel))
                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                            .addComponent(IRField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(80, 80, 80)
                                            .addComponent(SRLabel)))))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(R1Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(R0Field1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(R2Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(R2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(R3Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(R3Field, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(R4Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(R4Field, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(R5Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(R5Field, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(R6Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(R6Field, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(KeyboardField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SRField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1)
                                .addComponent(DisplayField, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IRLabel)
                    .addComponent(IRField, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SRLabel)
                    .addComponent(SRField, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PCLabel)
                    .addComponent(PCField, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KeyboardLabel)
                    .addComponent(KeyboardField, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ALabel)
                    .addComponent(AField, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DisplayLabel)
                    .addComponent(DisplayField, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(R0Label)
                            .addComponent(R0Field, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MemoryLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(R1Label)
                            .addComponent(R0Field1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(R2Label)
                            .addComponent(R2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(R3Label)
                            .addComponent(R3Field, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(R4Label)
                            .addComponent(R4Field, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(R5Label)
                            .addComponent(R5Field, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(R6Label)
                            .addComponent(R6Field, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(R7Label)
                            .addComponent(R7Field, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        openMenuItem.setText(resourceMap.getString("openMenuItem.text")); // NOI18N
        openMenuItem.setName("openMenuItem"); // NOI18N
        fileMenu.add(openMenuItem);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(microsim.MicrosimApp.class).getContext().getActionMap(MicrosimView.class, this);
        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        statusPanel.setName("statusPanel"); // NOI18N

        statusPanelSeparator.setName("statusPanelSeparator"); // NOI18N

        statusMessageLabel.setName("statusMessageLabel"); // NOI18N

        statusAnimationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusAnimationLabel.setName("statusAnimationLabel"); // NOI18N

        progressBar.setName("progressBar"); // NOI18N

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusPanelSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusMessageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusAnimationLabel)
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addComponent(statusPanelSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusMessageLabel)
                    .addComponent(statusAnimationLabel)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        PCField1.setEditable(false);
        PCField1.setMaximumSize(new java.awt.Dimension(8, 1));
        PCField1.setMinimumSize(new java.awt.Dimension(8, 1));
        PCField1.setName("PCField1"); // NOI18N
        PCField1.setPreferredSize(new java.awt.Dimension(8, 1));

        setComponent(mainPanel);
        setMenuBar(menuBar);
        setStatusBar(statusPanel);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AField;
    private javax.swing.JLabel ALabel;
    private javax.swing.JTextField DisplayField;
    private javax.swing.JLabel DisplayLabel;
    private javax.swing.JTextField IRField;
    private javax.swing.JLabel IRLabel;
    private javax.swing.JTextField KeyboardField;
    private javax.swing.JLabel KeyboardLabel;
    private javax.swing.JLabel MemoryLabel;
    private javax.swing.JList MemoryList;
    private javax.swing.JTextField PCField;
    private javax.swing.JTextField PCField1;
    private javax.swing.JLabel PCLabel;
    private javax.swing.JTextField R0Field;
    private javax.swing.JTextField R0Field1;
    private javax.swing.JLabel R0Label;
    private javax.swing.JLabel R1Label;
    private javax.swing.JTextField R2Field;
    private javax.swing.JLabel R2Label;
    private javax.swing.JTextField R3Field;
    private javax.swing.JLabel R3Label;
    private javax.swing.JTextField R4Field;
    private javax.swing.JLabel R4Label;
    private javax.swing.JTextField R5Field;
    private javax.swing.JLabel R5Label;
    private javax.swing.JTextField R6Field;
    private javax.swing.JLabel R6Label;
    private javax.swing.JTextField R7Field;
    private javax.swing.JLabel R7Label;
    private javax.swing.JTextField SRField;
    private javax.swing.JLabel SRLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel statusAnimationLabel;
    private javax.swing.JLabel statusMessageLabel;
    private javax.swing.JPanel statusPanel;
    // End of variables declaration//GEN-END:variables

    private final Timer messageTimer;
    private final Timer busyIconTimer;
    private final Icon idleIcon;
    private final Icon[] busyIcons = new Icon[15];
    private int busyIconIndex = 0;

    private JDialog aboutBox;
}
